Upload for command check in script.

diff --git a/scripts/install-git-hooks b/scripts/install-git-hooks
--- a/scripts/install-git-hooks
+++ b/scripts/install-git-hooks
@@ -1,4 +1,8 @@
 #!/bin/sh
 
 ln -sf ../../scripts/pre-commit.hook .git/hooks/pre-commit
-echo "OK"
+if [ "$?" -eq 0 ]; then
+  echo "OK"
+else
+  echo "Failed to install pre-commit.hook"
+fi
